/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/wallet": {
    /**
     * Баланс
     * @description available — свободные деньги, held — удержанные по заказам.
     */
    get: operations["get_api_wallet_balance"];
  };
  "/api/wallet/deposit": {
    /**
     * Пополнить счёт
     * @description Заглушка вместо платёжного провайдера: деньги зачисляются без оплаты. Нужна, чтобы покупку можно было довести до конца.
     */
    post: operations["post_api_wallet_deposit"];
  };
  "/api/games": {
    /**
     * Список активных игр
     * @description Без разделов: витрине они не нужны.
     */
    get: operations["get_api_games_list"];
  };
  "/api/games/{slug}": {
    /**
     * Карточка игры
     * @description То же, что в списке, плюс разделы со схемой атрибутов лота.
     */
    get: operations["get_api_games_show"];
  };
  "/health": {
    /**
     * Проверка живости
     * @description Ручка для healthcheck контейнера и балансировщика: ничего не проверяет, кроме того, что приложение отвечает.
     */
    get: operations["get_health"];
  };
  "/api/auth/register": {
    /**
     * Зарегистрировать аккаунт
     * @description Создаёт аккаунт в статусе pending и отправляет письмо со ссылкой подтверждения. Войти до подтверждения нельзя.
     */
    post: operations["post_api_auth_register"];
  };
  "/api/auth/confirm": {
    /**
     * Подтвердить почту
     * @description Ссылка из письма. Срабатывает один раз: вместе с подтверждением токен гасится.
     */
    get: operations["get_api_auth_confirm"];
  };
  "/api/auth/resend-confirmation": {
    /**
     * Выслать письмо подтверждения заново
     * @description Всегда отвечает 202, независимо от того, есть ли такой аккаунт и подтверждён ли он. Прошлый токен перестаёт работать.
     */
    post: operations["post_api_auth_resend_confirmation"];
  };
  "/api/auth/login": {
    /**
     * Войти и получить JWT
     * @description Маршрут нужен, чтобы check_path было на что указывать, а спеке — что описывать.
     */
    post: operations["post_api_auth_login"];
  };
  "/api/auth/me": {
    /** Текущий пользователь */
    get: operations["get_api_auth_me"];
  };
  "/api/users": {
    /**
     * Публичные профили
     * @description Почта и хеш пароля наружу не отдаются никогда.
     */
    get: operations["get_api_users_list"];
  };
  "/api/games/{slug}/offers": {
    /**
     * Лоты игры
     * @description Товары и услуги активных лотов игры, свежие сверху.
     */
    get: operations["get_api_offers_by_game"];
  };
  "/api/offers/{id}": {
    /**
     * Карточка лота
     * @description Описание, атрибуты, продавец и раздел с игрой.
     */
    get: operations["get_api_offers_show"];
  };
  "/api/orders": {
    /**
     * Купить лот
     * @description Создаёт заказ по снимку лота и удерживает деньги покупателя в эскроу. Товар выдаётся сразу, услуга ждёт продавца.
     */
    post: operations["post_api_orders_place"];
  };
  "/api/orders/{id}": {
    /**
     * Заказ
     * @description Виден только покупателю и продавцу. Выданные ключи лежат в deliveredItems.
     */
    get: operations["get_api_orders_show"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    DepositRequest: {
      /** Сумма в копейках: рубли с копейками во float — потерянная копейка. */
      amount: number;
    };
    RegistrationRequest: {
      email: string;
      /** Верхняя граница — не придирка, а предел bcrypt: всё после 72 байт молча отбрасывается. */
      password: string;
      displayName: string;
    };
    ResendConfirmationRequest: {
      email: string;
    };
    PlaceOrderRequest: {
      offerId: string;
      /** @default 1 */
      quantity?: number;
    };
    Money: {
      amount: number;
      /** @default RUB */
      currency?: string;
    };
    WalletView: {
      userId: string;
      available: components["schemas"]["Money"];
      held: components["schemas"]["Money"];
    };
    GameSummary: {
      id: number;
      slug: string;
      title: string;
      platforms: string[];
    };
    /** @enum {string} */
    SectionKind: "goods" | "service";
    SectionView: {
      id: number;
      title: string;
      kind: components["schemas"]["SectionKind"];
      commissionBasisPoints: number;
      attributeSchema: {
        [key: string]: unknown;
      };
    };
    GameDetails: {
      id: number;
      slug: string;
      title: string;
      platforms: string[];
      sections: components["schemas"]["SectionView"][];
    };
    /** @enum {string} */
    UserStatus: "pending" | "active" | "limited" | "banned";
    UserView: {
      id: string;
      displayName: string;
      status: components["schemas"]["UserStatus"];
      /** Format: date-time */
      registeredAt: string;
    };
    /** @enum {string} */
    DeliveryType: "auto" | "manual";
    OfferSummary: {
      id: string;
      title: string;
      price: components["schemas"]["Money"];
      deliveryType: components["schemas"]["DeliveryType"];
      stock?: number | null;
      sectionId: number;
      sectionTitle: string;
      kind: components["schemas"]["SectionKind"];
    };
    SectionContext: {
      id: number;
      title: string;
      kind: components["schemas"]["SectionKind"];
      commissionBasisPoints: number;
      gameSlug: string;
      gameTitle: string;
    };
    OfferDetails: {
      id: string;
      title: string;
      description: string;
      price: components["schemas"]["Money"];
      deliveryType: components["schemas"]["DeliveryType"];
      stock?: number | null;
      isPurchasable: boolean;
      attributes: {
        [key: string]: unknown;
      };
      section: components["schemas"]["SectionContext"];
      seller: components["schemas"]["UserView"];
    };
    /** @enum {string} */
    OrderStatus: "placed" | "paid" | "delivered" | "completed" | "cancelled" | "disputed" | "refunded";
    OfferSnapshot: {
      title: string;
      price: components["schemas"]["Money"];
      sectionId: number;
      /** @default [] */
      attributes?: {
        [key: string]: unknown;
      };
    };
    OrderView: {
      id: string;
      status: components["schemas"]["OrderStatus"];
      offerId: string;
      buyerId: string;
      sellerId: string;
      offer: components["schemas"]["OfferSnapshot"];
      quantity: number;
      amount: components["schemas"]["Money"];
      commission: components["schemas"]["Money"];
      payout: components["schemas"]["Money"];
      /** Format: date-time */
      placedAt: string;
      /** Format: date-time */
      paidAt?: string | null;
      /** Format: date-time */
      deliveredAt?: string | null;
      deliveredItems: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Баланс
   * @description available — свободные деньги, held — удержанные по заказам.
   */
  get_api_wallet_balance: {
    responses: {
      /** @description Баланс владельца токена */
      200: {
        content: {
          "application/json": components["schemas"]["WalletView"];
        };
      };
      /** @description Токен не передан, истёк или недействителен */
      401: {
        content: never;
      };
    };
  };
  /**
   * Пополнить счёт
   * @description Заглушка вместо платёжного провайдера: деньги зачисляются без оплаты. Нужна, чтобы покупку можно было довести до конца.
   */
  post_api_wallet_deposit: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DepositRequest"];
      };
    };
    responses: {
      /** @description Баланс после пополнения */
      200: {
        content: {
          "application/json": components["schemas"]["WalletView"];
        };
      };
      /** @description Токен не передан, истёк или недействителен */
      401: {
        content: never;
      };
      /** @description Сумма не прошла валидацию */
      422: {
        content: never;
      };
    };
  };
  /**
   * Список активных игр
   * @description Без разделов: витрине они не нужны.
   */
  get_api_games_list: {
    responses: {
      /** @description Игры, отсортированные по названию */
      200: {
        content: {
          "application/json": {
            items?: components["schemas"]["GameSummary"][];
          };
        };
      };
    };
  };
  /**
   * Карточка игры
   * @description То же, что в списке, плюс разделы со схемой атрибутов лота.
   */
  get_api_games_show: {
    parameters: {
      path: {
        /** @description Человекочитаемый идентификатор игры */
        slug: string;
      };
    };
    responses: {
      /** @description Игра с разделами */
      200: {
        content: {
          "application/json": components["schemas"]["GameDetails"];
        };
      };
      /** @description Игры с таким slug нет или она отключена */
      404: {
        content: never;
      };
    };
  };
  /**
   * Проверка живости
   * @description Ручка для healthcheck контейнера и балансировщика: ничего не проверяет, кроме того, что приложение отвечает.
   */
  get_health: {
    responses: {
      /** @description Приложение отвечает */
      200: {
        content: {
          "application/json": {
            /** @example ok */
            status?: string;
          };
        };
      };
    };
  };
  /**
   * Зарегистрировать аккаунт
   * @description Создаёт аккаунт в статусе pending и отправляет письмо со ссылкой подтверждения. Войти до подтверждения нельзя.
   */
  post_api_auth_register: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegistrationRequest"];
      };
    };
    responses: {
      /** @description Аккаунт создан, письмо отправлено */
      201: {
        content: {
          "application/json": components["schemas"]["UserView"];
        };
      };
      /** @description Почта уже занята */
      409: {
        content: never;
      };
      /** @description Данные не прошли валидацию */
      422: {
        content: never;
      };
    };
  };
  /**
   * Подтвердить почту
   * @description Ссылка из письма. Срабатывает один раз: вместе с подтверждением токен гасится.
   */
  get_api_auth_confirm: {
    parameters: {
      query: {
        /** @description Токен из письма */
        token: string;
      };
    };
    responses: {
      /** @description Почта подтверждена, аккаунт активен */
      200: {
        content: {
          "application/json": components["schemas"]["UserView"];
        };
      };
      /** @description Токен неизвестен, просрочен или уже использован */
      400: {
        content: never;
      };
    };
  };
  /**
   * Выслать письмо подтверждения заново
   * @description Всегда отвечает 202, независимо от того, есть ли такой аккаунт и подтверждён ли он. Прошлый токен перестаёт работать.
   */
  post_api_auth_resend_confirmation: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResendConfirmationRequest"];
      };
    };
    responses: {
      /** @description Запрос принят */
      202: {
        content: never;
      };
      /** @description Адрес не похож на почту */
      422: {
        content: never;
      };
    };
  };
  /**
   * Войти и получить JWT
   * @description Маршрут нужен, чтобы check_path было на что указывать, а спеке — что описывать.
   */
  post_api_auth_login: {
    requestBody: {
      content: {
        "application/json": {
          /**
           * Format: email
           * @example seller@universe.test
           */
          email: string;
          /**
           * Format: password
           * @example password
           */
          password: string;
        };
      };
    };
    responses: {
      /** @description Токен выдан */
      200: {
        content: {
          "application/json": {
            token?: string;
          };
        };
      };
      /** @description Неверная пара почта/пароль, либо почта не подтверждена, либо аккаунт заблокирован */
      401: {
        content: {
          "application/json": {
            /** @example 401 */
            code?: number;
            /** @example Подтвердите почту по ссылке из письма. */
            message?: string;
          };
        };
      };
    };
  };
  /** Текущий пользователь */
  get_api_auth_me: {
    responses: {
      /** @description Профиль владельца токена */
      200: {
        content: {
          "application/json": components["schemas"]["UserView"];
        };
      };
      /** @description Токен не передан, истёк или недействителен */
      401: {
        content: never;
      };
    };
  };
  /**
   * Публичные профили
   * @description Почта и хеш пароля наружу не отдаются никогда.
   */
  get_api_users_list: {
    responses: {
      /** @description Профили в порядке регистрации */
      200: {
        content: {
          "application/json": {
            items?: components["schemas"]["UserView"][];
          };
        };
      };
    };
  };
  /**
   * Лоты игры
   * @description Товары и услуги активных лотов игры, свежие сверху.
   */
  get_api_offers_by_game: {
    parameters: {
      query?: {
        /** @description Оставить только лоты этого раздела */
        section?: number | null;
        /** @description Оставить только товары или только услуги */
        kind?: "goods" | "service" | null;
      };
      path: {
        /** @description Человекочитаемый идентификатор игры */
        slug: string;
      };
    };
    responses: {
      /** @description Лоты игры */
      200: {
        content: {
          "application/json": {
            items?: components["schemas"]["OfferSummary"][];
          };
        };
      };
      /** @description Игры с таким slug нет или она отключена */
      404: {
        content: never;
      };
    };
  };
  /**
   * Карточка лота
   * @description Описание, атрибуты, продавец и раздел с игрой.
   */
  get_api_offers_show: {
    parameters: {
      path: {
        /** @description Идентификатор лота */
        id: string;
      };
    };
    responses: {
      /** @description Лот */
      200: {
        content: {
          "application/json": components["schemas"]["OfferDetails"];
        };
      };
      /** @description Лота с таким идентификатором нет или он не опубликован */
      404: {
        content: never;
      };
    };
  };
  /**
   * Купить лот
   * @description Создаёт заказ по снимку лота и удерживает деньги покупателя в эскроу. Товар выдаётся сразу, услуга ждёт продавца.
   */
  post_api_orders_place: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlaceOrderRequest"];
      };
    };
    responses: {
      /** @description Заказ создан и оплачен */
      201: {
        content: {
          "application/json": components["schemas"]["OrderView"];
        };
      };
      /** @description Токен не передан, истёк или недействителен */
      401: {
        content: never;
      };
      /** @description На кошельке не хватает денег */
      402: {
        content: never;
      };
      /** @description Это собственный лот покупателя */
      403: {
        content: never;
      };
      /** @description Лота с таким идентификатором нет */
      404: {
        content: never;
      };
      /** @description Лот снят с продажи или единиц меньше, чем запрошено */
      409: {
        content: never;
      };
      /** @description Запрос не прошёл валидацию */
      422: {
        content: never;
      };
    };
  };
  /**
   * Заказ
   * @description Виден только покупателю и продавцу. Выданные ключи лежат в deliveredItems.
   */
  get_api_orders_show: {
    parameters: {
      path: {
        /** @description Идентификатор заказа */
        id: string;
      };
    };
    responses: {
      /** @description Заказ */
      200: {
        content: {
          "application/json": components["schemas"]["OrderView"];
        };
      };
      /** @description Токен не передан, истёк или недействителен */
      401: {
        content: never;
      };
      /** @description Заказа нет или он чужой */
      404: {
        content: never;
      };
    };
  };
}
